import type { PremiumTemplate } from "./types";

const commonTech = ["Expo", "React Native/Web", "TypeScript", "Supabase", "Edge Functions-ready"];
const commonCompatibility = ["Android", "iOS", "Web", "White Label"];
const commonIntegrations = ["Supabase", "WhatsApp", "E-mail", "Analytics"];

export const premiumTemplates: PremiumTemplate[] = [
  {
    id: "tpl-hotel-premium",
    name: "Hotel Premium",
    slug: "hotel-premium",
    segment: "Aplicativo",
    category: "Hospitalidade",
    businessDnaSlug: "hotel",
    businessDnaName: "Hotel DNA™",
    description: "Reservas, quartos, tarifas e painel premium para hospedagens.",
    longDescription: "Template completo para hotéis e pousadas venderem reservas diretas, organizarem disponibilidade e criarem uma operação digital com experiência premium para hóspedes.",
    image: "placeholder://templates/hotel-premium",
    icon: "bed-outline",
    primaryColor: "#38bdf8",
    secondaryColor: "#0f172a",
    modulesCount: 9,
    compatibility: commonCompatibility,
    averageImplementationTime: "7 a 14 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.900",
    popularityScore: 94,
    isBestSeller: true,
    isNew: false,
    rating: 4.9,
    downloads: 128,
    deployments: 42,
    gallery: ["Reservas", "Quartos", "Calendário", "Painel"],
    features: ["Motor de reservas", "Gestão de quartos", "Calendário de ocupação", "Checkout", "Avaliações"],
    includedModules: ["Reservas", "Tarifas", "Quartos", "Pagamentos", "Painel de ocupação", "Notificações"],
    integrations: [...commonIntegrations, "Google Maps", "Pagamentos"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Premium",
    recommendedTemplateSlugs: ["turismo", "marketplace-completo"],
    relatedTemplateSlugs: ["turismo", "restaurante-delivery"],
    aiIntegrationContract: {
      recommendedPromptContext: ["tipo de hospedagem", "quantidade de quartos", "política de reservas"],
      personalizationInputs: ["marca", "cidade", "cores", "regras de diária"],
      generationBoundaries: ["não publicar sem revisão humana", "não alterar pagamentos sem escopo"],
    },
  },
  {
    id: "tpl-clinica-premium",
    name: "Clínica Premium",
    slug: "clinica-premium",
    segment: "Sistema Web",
    category: "Saúde",
    businessDnaSlug: "clinica",
    businessDnaName: "Clínica DNA™",
    description: "Agenda, pacientes, serviços e presença digital profissional.",
    longDescription: "Template premium para clínicas organizarem captação, agendamentos, retornos e relacionamento com pacientes em uma plataforma moderna.",
    image: "placeholder://templates/clinica-premium",
    icon: "medical-bag",
    primaryColor: "#2dd4bf",
    secondaryColor: "#0f172a",
    modulesCount: 8,
    compatibility: commonCompatibility,
    averageImplementationTime: "7 a 12 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.500",
    popularityScore: 91,
    isBestSeller: true,
    isNew: false,
    rating: 4.8,
    downloads: 104,
    deployments: 37,
    gallery: ["Agenda", "Pacientes", "Serviços", "Landing"],
    features: ["Agendamento", "Cadastro de pacientes", "Notificações", "Pré-atendimento", "Painel administrativo"],
    includedModules: ["Agenda", "Profissionais", "Pacientes", "Serviços", "Landing page", "Mensagens"],
    integrations: [...commonIntegrations, "Calendário"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Premium",
    recommendedTemplateSlugs: ["financeira", "escola"],
    relatedTemplateSlugs: ["academia", "barbearia"],
    aiIntegrationContract: {
      recommendedPromptContext: ["especialidades", "quantidade de profissionais", "fluxo de agenda"],
      personalizationInputs: ["marca", "serviços", "horários", "políticas"],
      generationBoundaries: ["não tratar dados sensíveis sem LGPD", "não gerar diagnóstico médico"],
    },
  },
  {
    id: "tpl-restaurante-delivery",
    name: "Restaurante Delivery",
    slug: "restaurante-delivery",
    segment: "Aplicativo",
    category: "Alimentação",
    businessDnaSlug: "restaurante",
    businessDnaName: "Restaurante DNA™",
    description: "Cardápio, pedidos, retirada, delivery e campanhas locais.",
    longDescription: "Template para restaurantes criarem canal próprio de pedidos com cardápio digital, checkout e ações de recompra.",
    image: "placeholder://templates/restaurante-delivery",
    icon: "silverware-fork-knife",
    primaryColor: "#fb7185",
    secondaryColor: "#1f2937",
    modulesCount: 7,
    compatibility: commonCompatibility,
    averageImplementationTime: "5 a 10 dias",
    badge: "Popular",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 3.900",
    popularityScore: 96,
    isBestSeller: true,
    isNew: false,
    rating: 4.9,
    downloads: 186,
    deployments: 61,
    gallery: ["Cardápio", "Pedidos", "Checkout", "Promoções"],
    features: ["Cardápio digital", "Carrinho", "Checkout", "Cupons", "Status de pedido"],
    includedModules: ["Produtos", "Combos", "Delivery", "Retirada", "Cupons", "Painel operacional"],
    integrations: [...commonIntegrations, "Pagamentos", "Impressão de pedidos"],
    technologies: commonTech,
    version: "1.1.0",
    recommendedPlan: "Growth",
    recommendedTemplateSlugs: ["loja-virtual", "delivery"],
    relatedTemplateSlugs: ["hotel-premium", "marketplace-completo"],
    aiIntegrationContract: {
      recommendedPromptContext: ["tipo de culinária", "região", "ticket médio"],
      personalizationInputs: ["cardápio", "horários", "taxas", "branding"],
      generationBoundaries: ["não executar pedido real", "não ativar pagamento automaticamente"],
    },
  },
  {
    id: "tpl-marketplace-completo",
    name: "Marketplace Completo",
    slug: "marketplace-completo",
    segment: "Marketplace",
    category: "Comércio",
    businessDnaSlug: "marketplace",
    businessDnaName: "Marketplace DNA™",
    description: "Vendedores, catálogo, comissões, pedidos e operação multi-fornecedor.",
    longDescription: "Template robusto para lançar marketplaces de nicho com onboarding de vendedores, catálogo, pedidos, comissões e governança.",
    image: "placeholder://templates/marketplace-completo",
    icon: "storefront-outline",
    primaryColor: "#22d3ee",
    secondaryColor: "#0f172a",
    modulesCount: 12,
    compatibility: commonCompatibility,
    averageImplementationTime: "15 a 30 dias",
    badge: "Enterprise",
    priceTier: "Enterprise",
    priceLabel: "Sob consulta",
    popularityScore: 89,
    isBestSeller: false,
    isNew: false,
    rating: 4.8,
    downloads: 76,
    deployments: 18,
    gallery: ["Vendedores", "Catálogo", "Pedidos", "Comissões"],
    features: ["Onboarding de vendedores", "Catálogo multi-fornecedor", "Comissões", "Moderação", "Painel de fornecedores"],
    includedModules: ["Vendedores", "Produtos", "Pedidos", "Comissões", "Moderação", "Relatórios", "Governança"],
    integrations: [...commonIntegrations, "Split de pagamento", "Logística"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Enterprise",
    recommendedTemplateSlugs: ["marketplace-multiempresa", "servicos-locais"],
    relatedTemplateSlugs: ["loja-virtual", "delivery"],
    aiIntegrationContract: {
      recommendedPromptContext: ["nicho", "tipo de vendedor", "modelo de comissão"],
      personalizationInputs: ["categorias", "regras", "políticas", "taxas"],
      generationBoundaries: ["não configurar split real sem revisão", "não criar regras fiscais automaticamente"],
    },
  },
  {
    id: "tpl-imobiliaria",
    name: "Imobiliária",
    slug: "imobiliaria",
    segment: "Sistema Web",
    category: "Serviços",
    businessDnaSlug: "imobiliaria",
    businessDnaName: "Imobiliária DNA™",
    description: "Imóveis, leads, filtros, visitas e painel comercial.",
    longDescription: "Template para imobiliárias e corretores captarem leads, exibirem imóveis e organizarem atendimento comercial.",
    image: "placeholder://templates/imobiliaria",
    icon: "home-city-outline",
    primaryColor: "#60a5fa",
    secondaryColor: "#0f172a",
    modulesCount: 8,
    compatibility: ["Web", "White Label", "Android", "iOS"],
    averageImplementationTime: "10 a 18 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.700",
    popularityScore: 84,
    isBestSeller: false,
    isNew: false,
    rating: 4.7,
    downloads: 71,
    deployments: 22,
    gallery: ["Imóveis", "Leads", "Filtros", "Visitas"],
    features: ["Catálogo de imóveis", "Filtros avançados", "Captação de leads", "Agendamento de visitas"],
    includedModules: ["Imóveis", "Leads", "CRM", "Visitas", "Landing pages", "Relatórios"],
    integrations: [...commonIntegrations, "Google Maps", "CRM"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Premium",
    recommendedTemplateSlugs: ["financeira", "construcao-civil"],
    relatedTemplateSlugs: ["marketplace-completo", "loja-virtual"],
    aiIntegrationContract: {
      recommendedPromptContext: ["região", "tipo de imóvel", "perfil de cliente"],
      personalizationInputs: ["carteira", "fotos", "corretores", "regras de contato"],
      generationBoundaries: ["não prometer financiamento", "não alterar dados de pagamento"],
    },
  },
  {
    id: "tpl-academia",
    name: "Academia",
    slug: "academia",
    segment: "Aplicativo",
    category: "Serviços",
    businessDnaSlug: "academia",
    businessDnaName: "Academia DNA™",
    description: "Planos, alunos, aulas, check-ins e comunidade.",
    longDescription: "Template para academias e studios gerenciarem alunos, venderem planos e criarem uma experiência digital recorrente.",
    image: "placeholder://templates/academia",
    icon: "weight-lifter",
    primaryColor: "#a3e635",
    secondaryColor: "#111827",
    modulesCount: 7,
    compatibility: commonCompatibility,
    averageImplementationTime: "6 a 12 dias",
    badge: "Popular",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 3.900",
    popularityScore: 86,
    isBestSeller: false,
    isNew: false,
    rating: 4.7,
    downloads: 93,
    deployments: 27,
    gallery: ["Planos", "Alunos", "Aulas", "Check-in"],
    features: ["Planos", "Agenda de aulas", "Check-in", "Comunidade", "Renovação"],
    includedModules: ["Alunos", "Planos", "Aulas", "Check-in", "Desafios", "Notificações"],
    integrations: [...commonIntegrations, "Check-in"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Growth",
    recommendedTemplateSlugs: ["clinica-premium", "barbearia"],
    relatedTemplateSlugs: ["escola", "servicos-locais"],
    aiIntegrationContract: {
      recommendedPromptContext: ["modalidades", "planos", "perfil dos alunos"],
      personalizationInputs: ["grade", "valores", "regras de acesso"],
      generationBoundaries: ["não criar cobrança real", "não alterar dados sensíveis"],
    },
  },
  {
    id: "tpl-barbearia",
    name: "Barbearia",
    slug: "barbearia",
    segment: "Aplicativo",
    category: "Serviços",
    businessDnaSlug: "barbearia",
    businessDnaName: "Barbearia DNA™",
    description: "Agenda, profissionais, serviços, pacotes e fidelização.",
    longDescription: "Template enxuto e premium para barbearias profissionalizarem agenda, vendas recorrentes e presença local.",
    image: "placeholder://templates/barbearia",
    icon: "content-cut",
    primaryColor: "#f59e0b",
    secondaryColor: "#111827",
    modulesCount: 6,
    compatibility: commonCompatibility,
    averageImplementationTime: "3 a 7 dias",
    badge: "Popular",
    priceTier: "Starter",
    priceLabel: "A partir de R$ 2.900",
    popularityScore: 88,
    isBestSeller: true,
    isNew: false,
    rating: 4.8,
    downloads: 147,
    deployments: 53,
    gallery: ["Agenda", "Serviços", "Profissionais", "Fidelidade"],
    features: ["Agendamento", "Serviços", "Profissionais", "Pacotes", "Lembretes"],
    includedModules: ["Agenda", "Serviços", "Profissionais", "Fidelidade", "Galeria"],
    integrations: [...commonIntegrations, "Calendário"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Starter",
    recommendedTemplateSlugs: ["academia", "servicos-locais"],
    relatedTemplateSlugs: ["clinica-premium", "restaurante-delivery"],
    aiIntegrationContract: {
      recommendedPromptContext: ["serviços", "profissionais", "horários"],
      personalizationInputs: ["preços", "agenda", "marca", "endereço"],
      generationBoundaries: ["não confirmar agenda real", "não ativar automações sem revisão"],
    },
  },
  {
    id: "tpl-servicos-locais",
    name: "Serviços Locais",
    slug: "servicos-locais",
    segment: "Marketplace",
    category: "Serviços",
    businessDnaSlug: "servicos-locais",
    businessDnaName: "Serviços Locais DNA™",
    description: "Pedidos, profissionais, propostas e operação local.",
    longDescription: "Template para conectar clientes e profissionais com pedidos, propostas, categorias e painel operacional.",
    image: "placeholder://templates/servicos-locais",
    icon: "account-hard-hat-outline",
    primaryColor: "#facc15",
    secondaryColor: "#111827",
    modulesCount: 10,
    compatibility: commonCompatibility,
    averageImplementationTime: "10 a 20 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 5.900",
    popularityScore: 90,
    isBestSeller: false,
    isNew: false,
    rating: 4.8,
    downloads: 119,
    deployments: 34,
    gallery: ["Pedidos", "Profissionais", "Propostas", "Categorias"],
    features: ["Pedidos", "Categorias", "Profissionais", "Propostas", "Chat operacional"],
    includedModules: ["Clientes", "Profissionais", "Pedidos", "Propostas", "Avaliações", "Comissões"],
    integrations: [...commonIntegrations, "Maps", "Notificações"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Premium",
    recommendedTemplateSlugs: ["marketplace-completo", "barbearia"],
    relatedTemplateSlugs: ["delivery", "academia"],
    aiIntegrationContract: {
      recommendedPromptContext: ["categorias", "raio", "modelo de comissão"],
      personalizationInputs: ["serviços", "regras", "papéis", "preços"],
      generationBoundaries: ["não mexer em pagamento", "não aprovar profissionais automaticamente"],
    },
  },
  {
    id: "tpl-loja-virtual",
    name: "Loja Virtual",
    slug: "loja-virtual",
    segment: "Site",
    category: "Comércio",
    businessDnaSlug: "loja-virtual",
    businessDnaName: "Loja Virtual DNA™",
    description: "Produtos, carrinho, checkout, campanhas e catálogo.",
    longDescription: "Template para lojas venderem produtos online com catálogo profissional, checkout preparado e módulos de crescimento.",
    image: "placeholder://templates/loja-virtual",
    icon: "shopping-outline",
    primaryColor: "#c084fc",
    secondaryColor: "#111827",
    modulesCount: 8,
    compatibility: commonCompatibility,
    averageImplementationTime: "7 a 14 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.200",
    popularityScore: 87,
    isBestSeller: false,
    isNew: false,
    rating: 4.7,
    downloads: 112,
    deployments: 31,
    gallery: ["Produtos", "Carrinho", "Checkout", "Campanhas"],
    features: ["Produtos", "Variações", "Carrinho", "Pedidos", "Promoções"],
    includedModules: ["Catálogo", "Carrinho", "Pedidos", "Cupons", "Estoque", "Landing"],
    integrations: [...commonIntegrations, "Frete", "Pagamentos"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Growth",
    recommendedTemplateSlugs: ["restaurante-delivery", "marketplace-completo"],
    relatedTemplateSlugs: ["delivery", "financeira"],
    aiIntegrationContract: {
      recommendedPromptContext: ["categoria", "ticket médio", "logística"],
      personalizationInputs: ["produtos", "preços", "frete", "marca"],
      generationBoundaries: ["não publicar produtos sem revisão", "não configurar pagamento real"],
    },
  },
  {
    id: "tpl-financeira",
    name: "Financeira",
    slug: "financeira",
    segment: "Sistema Web",
    category: "Finanças",
    businessDnaSlug: "financeira",
    businessDnaName: "Financeira DNA™",
    description: "Leads, simulações, propostas e pipeline comercial.",
    longDescription: "Template para operações financeiras captarem clientes, simularem propostas e organizarem atendimento comercial com governança.",
    image: "placeholder://templates/financeira",
    icon: "finance",
    primaryColor: "#4ade80",
    secondaryColor: "#0f172a",
    modulesCount: 9,
    compatibility: ["Web", "White Label", "Android", "iOS"],
    averageImplementationTime: "12 a 24 dias",
    badge: "Enterprise",
    priceTier: "Enterprise",
    priceLabel: "Sob consulta",
    popularityScore: 80,
    isBestSeller: false,
    isNew: true,
    rating: 4.6,
    downloads: 44,
    deployments: 11,
    gallery: ["Simulações", "Leads", "Propostas", "Pipeline"],
    features: ["Simulações", "Leads", "Propostas", "Pipeline", "Documentos"],
    includedModules: ["CRM", "Simulação", "Documentos", "Propostas", "Relatórios"],
    integrations: [...commonIntegrations, "CRM", "Documentos"],
    technologies: commonTech,
    version: "0.9.0",
    recommendedPlan: "Enterprise",
    recommendedTemplateSlugs: ["imobiliaria", "clinica-premium"],
    relatedTemplateSlugs: ["construcao-civil", "loja-virtual"],
    aiIntegrationContract: {
      recommendedPromptContext: ["produto financeiro", "regras", "perfil de cliente"],
      personalizationInputs: ["campos", "documentos", "políticas"],
      generationBoundaries: ["não tomar decisão de crédito", "não armazenar dado sensível sem LGPD"],
    },
  },
  {
    id: "tpl-construcao-civil",
    name: "Construção Civil",
    slug: "construcao-civil",
    segment: "Sistema Web",
    category: "Construção",
    businessDnaSlug: "construcao-civil",
    businessDnaName: "Construção Civil DNA™",
    description: "Obras, orçamentos, etapas, equipe e acompanhamento.",
    longDescription: "Template para construtoras e equipes acompanharem obras, orçamentos, materiais e relatórios executivos.",
    image: "placeholder://templates/construcao-civil",
    icon: "hammer-wrench",
    primaryColor: "#fb923c",
    secondaryColor: "#111827",
    modulesCount: 8,
    compatibility: ["Web", "Android", "iOS", "White Label"],
    averageImplementationTime: "10 a 20 dias",
    badge: "Novo",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 5.200",
    popularityScore: 73,
    isBestSeller: false,
    isNew: true,
    rating: 4.6,
    downloads: 38,
    deployments: 9,
    gallery: ["Obras", "Etapas", "Orçamentos", "Relatórios"],
    features: ["Obras", "Orçamentos", "Etapas", "Equipe", "Relatórios"],
    includedModules: ["Obras", "Materiais", "Diário", "Fotos", "Equipe", "Financeiro"],
    integrations: [...commonIntegrations, "Arquivos"],
    technologies: commonTech,
    version: "0.9.0",
    recommendedPlan: "Premium",
    recommendedTemplateSlugs: ["imobiliaria", "financeira"],
    relatedTemplateSlugs: ["servicos-locais", "marketplace-completo"],
    aiIntegrationContract: {
      recommendedPromptContext: ["tipo de obra", "etapas", "papéis"],
      personalizationInputs: ["checklists", "documentos", "relatórios"],
      generationBoundaries: ["não gerar contrato legal final", "não alterar financeiro real"],
    },
  },
  {
    id: "tpl-turismo",
    name: "Turismo",
    slug: "turismo",
    segment: "Aplicativo",
    category: "Turismo",
    businessDnaSlug: "turismo",
    businessDnaName: "Turismo DNA™",
    description: "Roteiros, experiências, reservas e parceiros.",
    longDescription: "Template para agências, guias e destinos venderem experiências, pacotes e roteiros com canal digital próprio.",
    image: "placeholder://templates/turismo",
    icon: "map-marker-path",
    primaryColor: "#2dd4bf",
    secondaryColor: "#0f172a",
    modulesCount: 8,
    compatibility: commonCompatibility,
    averageImplementationTime: "8 a 16 dias",
    badge: "Novo",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.600",
    popularityScore: 77,
    isBestSeller: false,
    isNew: true,
    rating: 4.7,
    downloads: 52,
    deployments: 13,
    gallery: ["Roteiros", "Experiências", "Reservas", "Mapa"],
    features: ["Roteiros", "Experiências", "Reservas", "Parceiros", "Mapa"],
    includedModules: ["Roteiros", "Agenda", "Checkout", "Parceiros", "Avaliações"],
    integrations: [...commonIntegrations, "Google Maps"],
    technologies: commonTech,
    version: "0.9.0",
    recommendedPlan: "Growth",
    recommendedTemplateSlugs: ["hotel-premium", "marketplace-completo"],
    relatedTemplateSlugs: ["restaurante-delivery", "loja-virtual"],
    aiIntegrationContract: {
      recommendedPromptContext: ["destino", "experiências", "parceiros"],
      personalizationInputs: ["roteiros", "preços", "políticas"],
      generationBoundaries: ["não publicar reserva real", "não ativar cobrança sem revisão"],
    },
  },
  {
    id: "tpl-escola",
    name: "Escola",
    slug: "escola",
    segment: "Sistema Web",
    category: "Educação",
    businessDnaSlug: "escola",
    businessDnaName: "Escola DNA™",
    description: "Cursos, alunos, aulas, progresso e assinatura.",
    longDescription: "Template para escolas, cursos e treinamentos criarem ambiente digital de aprendizado com área do aluno e recorrência.",
    image: "placeholder://templates/escola",
    icon: "school-outline",
    primaryColor: "#818cf8",
    secondaryColor: "#111827",
    modulesCount: 8,
    compatibility: ["Web", "Android", "iOS", "White Label"],
    averageImplementationTime: "8 a 16 dias",
    badge: "Premium",
    priceTier: "Premium",
    priceLabel: "A partir de R$ 4.400",
    popularityScore: 82,
    isBestSeller: false,
    isNew: false,
    rating: 4.7,
    downloads: 67,
    deployments: 19,
    gallery: ["Cursos", "Aulas", "Alunos", "Progresso"],
    features: ["Cursos", "Aulas", "Alunos", "Progresso", "Área do aluno"],
    includedModules: ["Cursos", "Aulas", "Certificados", "Comunidade", "Assinaturas"],
    integrations: [...commonIntegrations, "Vídeo"],
    technologies: commonTech,
    version: "1.0.0",
    recommendedPlan: "Growth",
    recommendedTemplateSlugs: ["clinica-premium", "igreja"],
    relatedTemplateSlugs: ["academia", "loja-virtual"],
    aiIntegrationContract: {
      recommendedPromptContext: ["tipo de curso", "módulos", "modelo de cobrança"],
      personalizationInputs: ["conteúdo", "aulas", "perfil do aluno"],
      generationBoundaries: ["não publicar conteúdo sem revisão", "não cobrar sem integração aprovada"],
    },
  },
  {
    id: "tpl-igreja",
    name: "Igreja",
    slug: "igreja",
    segment: "Aplicativo",
    category: "Comunidade",
    businessDnaSlug: "igreja",
    businessDnaName: "Igreja DNA™",
    description: "Comunidade, eventos, doações, grupos e comunicação.",
    longDescription: "Template para comunidades e igrejas organizarem comunicação, eventos, doações e relacionamento com membros.",
    image: "placeholder://templates/igreja",
    icon: "church",
    primaryColor: "#fbbf24",
    secondaryColor: "#1f2937",
    modulesCount: 6,
    compatibility: commonCompatibility,
    averageImplementationTime: "5 a 12 dias",
    badge: "Novo",
    priceTier: "Starter",
    priceLabel: "A partir de R$ 2.900",
    popularityScore: 69,
    isBestSeller: false,
    isNew: true,
    rating: 4.6,
    downloads: 35,
    deployments: 8,
    gallery: ["Eventos", "Avisos", "Doações", "Grupos"],
    features: ["Eventos", "Avisos", "Doações", "Grupos", "Conteúdo"],
    includedModules: ["Comunidade", "Eventos", "Doações", "Avisos", "Conteúdo"],
    integrations: [...commonIntegrations, "Vídeo"],
    technologies: commonTech,
    version: "0.9.0",
    recommendedPlan: "Starter",
    recommendedTemplateSlugs: ["escola", "servicos-locais"],
    relatedTemplateSlugs: ["turismo", "academia"],
    aiIntegrationContract: {
      recommendedPromptContext: ["tamanho da comunidade", "eventos", "canais atuais"],
      personalizationInputs: ["agenda", "conteúdos", "formas de contribuição"],
      generationBoundaries: ["não ativar doações reais", "não publicar conteúdo sensível"],
    },
  },
  {
    id: "tpl-marketplace-multiempresa",
    name: "Marketplace Multiempresa",
    slug: "marketplace-multiempresa",
    segment: "Empresa Digital",
    category: "Comércio",
    businessDnaSlug: "marketplace",
    businessDnaName: "Marketplace DNA™",
    description: "Marketplace enterprise com múltiplas empresas, planos e governança.",
    longDescription: "Template enterprise para redes e operações multiempresa criarem ecossistemas digitais com controle, planos, fornecedores e governança.",
    image: "placeholder://templates/marketplace-multiempresa",
    icon: "domain",
    primaryColor: "#67e8f9",
    secondaryColor: "#020617",
    modulesCount: 15,
    compatibility: commonCompatibility,
    averageImplementationTime: "20 a 40 dias",
    badge: "Enterprise",
    priceTier: "Enterprise",
    priceLabel: "Sob consulta",
    popularityScore: 85,
    isBestSeller: false,
    isNew: true,
    rating: 4.9,
    downloads: 41,
    deployments: 7,
    gallery: ["Empresas", "Fornecedores", "Planos", "Governança"],
    features: ["Multiempresa", "Fornecedores", "Planos", "Comissões", "Governança", "Painel executivo"],
    includedModules: ["Tenants", "Planos", "Fornecedores", "Produtos", "Pedidos", "Comissões", "Security Center"],
    integrations: [...commonIntegrations, "Split", "Observabilidade", "Publicação"],
    technologies: commonTech,
    version: "0.8.0",
    recommendedPlan: "Enterprise",
    recommendedTemplateSlugs: ["marketplace-completo", "servicos-locais"],
    relatedTemplateSlugs: ["financeira", "hotel-premium"],
    aiIntegrationContract: {
      recommendedPromptContext: ["modelo de rede", "papéis", "regras de monetização"],
      personalizationInputs: ["planos", "governança", "categorias", "políticas"],
      generationBoundaries: ["não provisionar Data Plane automaticamente", "não configurar billing real sem aprovação"],
    },
  },
];

export const marketplaceSegments = Array.from(new Set(premiumTemplates.map((template) => template.segment)));
export const marketplaceCategories = Array.from(new Set(premiumTemplates.map((template) => template.category)));

export function findPremiumTemplateBySlug(slug: string) {
  return premiumTemplates.find((template) => template.slug === slug);
}

export function getPremiumTemplatesBySlugs(slugs: string[]) {
  return slugs
    .map((slug) => findPremiumTemplateBySlug(slug))
    .filter((template): template is PremiumTemplate => Boolean(template));
}
