import type { BusinessDna } from "./types";

const commonIntegrations = ["Supabase", "E-mail", "WhatsApp", "Analytics", "Pagamentos"];
const commonPremium = ["White Label", "Publishing Center™", "Growth Center™", "Automações avançadas"];

export const businessDnaCatalog: BusinessDna[] = [
  {
    id: "dna-hotel",
    name: "Hotel",
    slug: "hotel",
    category: "Hospitalidade",
    segment: "B2C",
    description: "Reservas, quartos, pagamentos e painel de ocupação.",
    commercialDescription: "Um Business DNA™ para hotéis, pousadas e hospedagens que precisam vender reservas, controlar disponibilidade e profissionalizar a experiência do hóspede.",
    icon: "bed-outline",
    primaryColor: "#38bdf8",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/hotel",
    maturity: "premium",
    defaultFeatures: ["Reservas online", "Gestão de quartos", "Calendário de ocupação", "Checkout", "Painel da hospedagem"],
    availableModules: ["Motor de reservas", "Tarifas por temporada", "Avaliações", "Cupons", "Relatórios de ocupação"],
    supportedIntegrations: [...commonIntegrations, "Google Maps"],
    premiumResources: [...commonPremium, "Gestão multiunidade", "Regras de diária dinâmica"],
    averageImplementationTime: "7 a 14 dias",
    benefits: ["Reduz atendimento manual", "Organiza disponibilidade", "Aumenta reservas diretas"],
    useCases: ["Pousadas locais", "Hotéis boutique", "Guias de hospedagem"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["tipo de hospedagem", "quantidade de quartos", "politica de cancelamento"],
      requiredInputs: ["nome da marca", "cidades atendidas", "meios de pagamento"],
      suggestedOutputs: ["mapa de reservas", "copy comercial", "checklist de publicação"],
    },
  },
  {
    id: "dna-restaurante",
    name: "Restaurante",
    slug: "restaurante",
    category: "Comércio",
    segment: "Operação Local",
    description: "Cardápio, pedidos, delivery e fidelização.",
    commercialDescription: "Estrutura digital para restaurantes que querem vender mais, organizar pedidos e criar relacionamento direto com clientes.",
    icon: "silverware-fork-knife",
    primaryColor: "#fb7185",
    secondaryColor: "#1f2937",
    image: "placeholder://business-dna/restaurante",
    maturity: "validated",
    defaultFeatures: ["Cardápio digital", "Pedidos", "Retirada/delivery", "Cupons", "Painel de operação"],
    availableModules: ["Programa de fidelidade", "Mesas e reservas", "Combos", "Campanhas sazonais"],
    supportedIntegrations: [...commonIntegrations, "Impressão de pedidos"],
    premiumResources: [...commonPremium, "Cardápio multiunidade"],
    averageImplementationTime: "5 a 10 dias",
    benefits: ["Melhora conversão", "Centraliza pedidos", "Fortalece canal próprio"],
    useCases: ["Restaurantes", "Lanchonetes", "Cafeterias"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["tipo de culinária", "região de entrega", "ticket médio"],
      requiredInputs: ["cardápio", "horários", "formas de entrega"],
      suggestedOutputs: ["landing de venda", "campanhas", "fluxos de pedido"],
    },
  },
  {
    id: "dna-clinica",
    name: "Clínica",
    slug: "clinica",
    category: "Saúde",
    segment: "B2C",
    description: "Agendas, pacientes, atendimento e recorrência.",
    commercialDescription: "Modelo para clínicas que precisam captar pacientes, organizar agendamentos, melhorar comunicação e criar presença digital profissional.",
    icon: "medical-bag",
    primaryColor: "#2dd4bf",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/clinica",
    maturity: "premium",
    defaultFeatures: ["Agendamento", "Cadastro de pacientes", "Serviços", "Notificações", "Painel administrativo"],
    availableModules: ["Pré-atendimento", "Convênios", "Retorno automático", "Agenda por profissional"],
    supportedIntegrations: [...commonIntegrations, "Calendário"],
    premiumResources: [...commonPremium, "Triagem inteligente"],
    averageImplementationTime: "7 a 12 dias",
    benefits: ["Reduz faltas", "Organiza agenda", "Aumenta captação"],
    useCases: ["Clínicas médicas", "Odontologia", "Estética"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["especialidades", "quantidade de profissionais", "fluxo de agenda"],
      requiredInputs: ["serviços", "horários", "politicas de atendimento"],
      suggestedOutputs: ["jornada do paciente", "mensagens automáticas", "landing page"],
    },
  },
  {
    id: "dna-academia",
    name: "Academia",
    slug: "academia",
    category: "Serviços",
    segment: "Assinatura",
    description: "Planos, alunos, check-ins e evolução.",
    commercialDescription: "DNA para academias, boxes e studios que precisam vender planos, acompanhar alunos e criar uma comunidade digital.",
    icon: "weight-lifter",
    primaryColor: "#a3e635",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/academia",
    maturity: "validated",
    defaultFeatures: ["Planos", "Alunos", "Check-in", "Agenda de aulas", "Painel do gestor"],
    availableModules: ["Treinos", "Avaliações", "Desafios", "Comunidade", "Renovação automática"],
    supportedIntegrations: [...commonIntegrations, "Catraca/Check-in"],
    premiumResources: [...commonPremium, "Desafios gamificados"],
    averageImplementationTime: "6 a 12 dias",
    benefits: ["Aumenta retenção", "Facilita renovação", "Engaja alunos"],
    useCases: ["Academias", "Studios", "Cross training"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["modalidades", "planos", "perfil dos alunos"],
      requiredInputs: ["grade de aulas", "valores", "regras de acesso"],
      suggestedOutputs: ["campanhas de matrícula", "fluxos de retenção", "painel de alunos"],
    },
  },
  {
    id: "dna-barbearia",
    name: "Barbearia",
    slug: "barbearia",
    category: "Serviços",
    segment: "Operação Local",
    description: "Agenda, profissionais, pacotes e fidelização.",
    commercialDescription: "Estrutura rápida para barbearias que querem profissionalizar agenda, divulgar serviços e vender pacotes recorrentes.",
    icon: "content-cut",
    primaryColor: "#f59e0b",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/barbearia",
    maturity: "validated",
    defaultFeatures: ["Agendamento", "Serviços", "Profissionais", "Galeria", "Fidelidade"],
    availableModules: ["Pacotes", "Assinatura mensal", "Cupons", "Lembretes"],
    supportedIntegrations: [...commonIntegrations, "Calendário"],
    premiumResources: [...commonPremium, "Clube de assinatura"],
    averageImplementationTime: "3 a 7 dias",
    benefits: ["Organiza horários", "Reduz no-show", "Vende recorrência"],
    useCases: ["Barbearias", "Salões masculinos", "Estúdios de beleza"],
    recommendedPlan: "Starter",
    aiPreparationContract: {
      briefingHints: ["serviços", "profissionais", "horários de pico"],
      requiredInputs: ["tabela de preços", "agenda", "endereços"],
      suggestedOutputs: ["copy local", "fluxo de agendamento", "campanhas"],
    },
  },
  {
    id: "dna-imobiliaria",
    name: "Imobiliária",
    slug: "imobiliaria",
    category: "Serviços",
    segment: "B2B",
    description: "Imóveis, leads, visitas e propostas.",
    commercialDescription: "DNA para imobiliárias que precisam captar leads, organizar imóveis, agendar visitas e dar mais velocidade comercial.",
    icon: "home-city-outline",
    primaryColor: "#60a5fa",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/imobiliaria",
    maturity: "premium",
    defaultFeatures: ["Catálogo de imóveis", "Leads", "Filtros", "Agendamento de visitas", "Painel comercial"],
    availableModules: ["CRM", "Simulação", "Captação de proprietários", "Tour virtual"],
    supportedIntegrations: [...commonIntegrations, "Maps", "CRM"],
    premiumResources: [...commonPremium, "Esteira comercial"],
    averageImplementationTime: "10 a 18 dias",
    benefits: ["Aumenta leads", "Organiza carteira", "Acelera atendimento"],
    useCases: ["Imobiliárias", "Corretores", "Lançamentos"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["tipo de imóvel", "região", "perfil de compra"],
      requiredInputs: ["carteira", "regras de contato", "fotos"],
      suggestedOutputs: ["landing de captação", "funil de leads", "copy de imóveis"],
    },
  },
  {
    id: "dna-delivery",
    name: "Delivery",
    slug: "delivery",
    category: "Comércio",
    segment: "Operação Local",
    description: "Catálogo, checkout, status e entregas.",
    commercialDescription: "Modelo de delivery próprio para empresas que querem vender sem depender apenas de marketplaces externos.",
    icon: "moped-outline",
    primaryColor: "#f97316",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/delivery",
    maturity: "validated",
    defaultFeatures: ["Catálogo", "Carrinho", "Checkout", "Status do pedido", "Áreas de entrega"],
    availableModules: ["Roteirização", "Cupons", "Taxas dinâmicas", "Programa de fidelidade"],
    supportedIntegrations: [...commonIntegrations, "Maps"],
    premiumResources: [...commonPremium, "Entrega multiunidade"],
    averageImplementationTime: "5 a 10 dias",
    benefits: ["Cria canal próprio", "Reduz dependência", "Melhora recompra"],
    useCases: ["Restaurantes", "Mercadinhos", "Farmácias"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["produtos", "raio de entrega", "taxas"],
      requiredInputs: ["catálogo", "formas de pagamento", "horários"],
      suggestedOutputs: ["fluxo de checkout", "campanhas", "notificações"],
    },
  },
  {
    id: "dna-loja-virtual",
    name: "Loja Virtual",
    slug: "loja-virtual",
    category: "Comércio",
    segment: "B2C",
    description: "Produtos, carrinho, pedidos e campanhas.",
    commercialDescription: "Base para lojas que precisam vender produtos online com catálogo, checkout e crescimento digital.",
    icon: "shopping-outline",
    primaryColor: "#c084fc",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/loja-virtual",
    maturity: "validated",
    defaultFeatures: ["Produtos", "Variações", "Carrinho", "Pedidos", "Promoções"],
    availableModules: ["Cupons", "Estoque", "Frete", "Reviews", "Upsell"],
    supportedIntegrations: [...commonIntegrations, "Frete"],
    premiumResources: [...commonPremium, "Campanhas automatizadas"],
    averageImplementationTime: "7 a 14 dias",
    benefits: ["Vende 24/7", "Organiza catálogo", "Aumenta ticket médio"],
    useCases: ["Lojas locais", "Marcas autorais", "Catálogos B2C"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["categoria de produtos", "ticket médio", "logística"],
      requiredInputs: ["produtos", "preços", "politica de troca"],
      suggestedOutputs: ["páginas de venda", "campanhas", "estrutura de categorias"],
    },
  },
  {
    id: "dna-marketplace",
    name: "Marketplace",
    slug: "marketplace",
    category: "Comércio",
    segment: "Marketplace",
    description: "Vendedores, catálogo, pedidos e repasses.",
    commercialDescription: "DNA para negócios que conectam compradores e vendedores em uma plataforma digital com operação multi-fornecedor.",
    icon: "storefront-outline",
    primaryColor: "#22d3ee",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/marketplace",
    maturity: "enterprise",
    defaultFeatures: ["Vendedores", "Catálogo", "Pedidos", "Comissões", "Painel de fornecedores"],
    availableModules: ["Split", "Moderação", "Logística", "Ranking", "Onboarding de vendedores"],
    supportedIntegrations: [...commonIntegrations, "Split de pagamento", "Logística"],
    premiumResources: [...commonPremium, "Governança multi-fornecedor"],
    averageImplementationTime: "15 a 30 dias",
    benefits: ["Cria ecossistema", "Escala oferta", "Monetiza com comissão"],
    useCases: ["Marketplaces locais", "Verticais de nicho", "Redes de fornecedores"],
    recommendedPlan: "Enterprise",
    aiPreparationContract: {
      briefingHints: ["tipo de vendedor", "regra de comissão", "categoria principal"],
      requiredInputs: ["modelo de repasse", "políticas", "papéis de usuário"],
      suggestedOutputs: ["arquitetura de marketplace", "fluxo de onboarding", "regras comerciais"],
    },
  },
  {
    id: "dna-servicos-locais",
    name: "Serviços Locais",
    slug: "servicos-locais",
    category: "Serviços",
    segment: "Marketplace",
    description: "Pedidos, profissionais, propostas e agenda.",
    commercialDescription: "DNA para conectar clientes a prestadores de serviços com pedidos, propostas e acompanhamento operacional.",
    icon: "account-hard-hat-outline",
    primaryColor: "#facc15",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/servicos-locais",
    maturity: "premium",
    defaultFeatures: ["Pedidos", "Profissionais", "Propostas", "Categorias", "Chat operacional"],
    availableModules: ["Geolocalização", "Urgência", "Comissões", "Avaliações", "Assinatura profissional"],
    supportedIntegrations: [...commonIntegrations, "Maps", "Notificações"],
    premiumResources: [...commonPremium, "Distribuição inteligente de pedidos"],
    averageImplementationTime: "10 a 20 dias",
    benefits: ["Conecta demanda e oferta", "Monetiza profissionais", "Organiza operação local"],
    useCases: ["Serviços residenciais", "Manutenção", "Redes locais"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["categorias", "raio de atendimento", "modelo de comissão"],
      requiredInputs: ["regras de pedido", "papéis", "precificação"],
      suggestedOutputs: ["jornada cliente/profissional", "políticas", "campanhas de aquisição"],
    },
  },
  {
    id: "dna-escola",
    name: "Escola",
    slug: "escola",
    category: "Educação",
    segment: "Assinatura",
    description: "Cursos, alunos, aulas e assinaturas.",
    commercialDescription: "Base para escolas, cursos e infoprodutores criarem ambiente digital de aprendizado e gestão.",
    icon: "school-outline",
    primaryColor: "#818cf8",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/escola",
    maturity: "validated",
    defaultFeatures: ["Cursos", "Aulas", "Alunos", "Progresso", "Área do aluno"],
    availableModules: ["Certificados", "Comunidade", "Assinaturas", "Quiz", "Conteúdo liberado por etapa"],
    supportedIntegrations: [...commonIntegrations, "Vídeo"],
    premiumResources: [...commonPremium, "Trilhas de aprendizado"],
    averageImplementationTime: "8 a 16 dias",
    benefits: ["Organiza ensino", "Gera recorrência", "Escala conteúdo"],
    useCases: ["Cursos online", "Escolas livres", "Treinamentos internos"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["tipo de curso", "formato de aula", "modelo de cobrança"],
      requiredInputs: ["conteúdos", "módulos", "perfil do aluno"],
      suggestedOutputs: ["trilha de curso", "landing", "emails de engajamento"],
    },
  },
  {
    id: "dna-financeira",
    name: "Financeira",
    slug: "financeira",
    category: "Finanças",
    segment: "B2B",
    description: "Clientes, simulações, propostas e gestão.",
    commercialDescription: "Modelo para operações financeiras que precisam captar clientes, organizar propostas e acompanhar funil comercial.",
    icon: "finance",
    primaryColor: "#4ade80",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/financeira",
    maturity: "premium",
    defaultFeatures: ["Simulações", "Leads", "Propostas", "Pipeline", "Painel gerencial"],
    availableModules: ["Score interno", "Documentos", "Pré-aprovação", "Esteira de atendimento"],
    supportedIntegrations: [...commonIntegrations, "CRM", "Documentos"],
    premiumResources: [...commonPremium, "Funil financeiro avançado"],
    averageImplementationTime: "12 a 24 dias",
    benefits: ["Aumenta conversão", "Padroniza propostas", "Melhora governança"],
    useCases: ["Correspondentes", "Fintechs locais", "Consultorias financeiras"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["produto financeiro", "regras comerciais", "perfil de cliente"],
      requiredInputs: ["campos de simulação", "documentos", "políticas"],
      suggestedOutputs: ["funil de proposta", "copy de captação", "checklist LGPD"],
    },
  },
  {
    id: "dna-igreja",
    name: "Igreja",
    slug: "igreja",
    category: "Comunidade",
    segment: "B2C",
    description: "Comunidade, eventos, doações e comunicação.",
    commercialDescription: "DNA para igrejas e comunidades centralizarem comunicação, eventos, contribuições e relacionamento com membros.",
    icon: "church",
    primaryColor: "#fbbf24",
    secondaryColor: "#1f2937",
    image: "placeholder://business-dna/igreja",
    maturity: "starter",
    defaultFeatures: ["Eventos", "Avisos", "Doações", "Grupos", "Conteúdo"],
    availableModules: ["Escalas", "Pedidos de oração", "Cursos", "Transmissões"],
    supportedIntegrations: [...commonIntegrations, "Vídeo"],
    premiumResources: [...commonPremium, "Gestão de comunidade"],
    averageImplementationTime: "5 a 12 dias",
    benefits: ["Centraliza comunicação", "Engaja membros", "Facilita contribuições"],
    useCases: ["Igrejas", "Comunidades", "Projetos sociais"],
    recommendedPlan: "Starter",
    aiPreparationContract: {
      briefingHints: ["tamanho da comunidade", "agenda", "canais atuais"],
      requiredInputs: ["eventos", "conteúdos", "formas de contribuição"],
      suggestedOutputs: ["calendário editorial", "fluxos de comunicação", "landing institucional"],
    },
  },
  {
    id: "dna-construcao-civil",
    name: "Construção Civil",
    slug: "construcao-civil",
    category: "Construção",
    segment: "B2B",
    description: "Obras, equipes, orçamentos e acompanhamento.",
    commercialDescription: "Modelo para construtoras, prestadores e equipes acompanharem obras, orçamentos, clientes e etapas.",
    icon: "hammer-wrench",
    primaryColor: "#fb923c",
    secondaryColor: "#111827",
    image: "placeholder://business-dna/construcao-civil",
    maturity: "validated",
    defaultFeatures: ["Obras", "Orçamentos", "Etapas", "Equipe", "Painel de acompanhamento"],
    availableModules: ["Materiais", "Diário de obra", "Financeiro", "Fotos por etapa", "Relatórios"],
    supportedIntegrations: [...commonIntegrations, "Arquivos"],
    premiumResources: [...commonPremium, "Relatórios executivos de obra"],
    averageImplementationTime: "10 a 20 dias",
    benefits: ["Organiza execução", "Aumenta transparência", "Reduz retrabalho"],
    useCases: ["Construtoras", "Reformas", "Empreiteiras"],
    recommendedPlan: "Premium",
    aiPreparationContract: {
      briefingHints: ["tipo de obra", "etapas", "papéis da equipe"],
      requiredInputs: ["processo de orçamento", "documentos", "checklists"],
      suggestedOutputs: ["fluxo de obra", "painel de status", "modelo de relatório"],
    },
  },
  {
    id: "dna-turismo",
    name: "Turismo",
    slug: "turismo",
    category: "Turismo",
    segment: "B2C",
    description: "Roteiros, reservas, experiências e parceiros.",
    commercialDescription: "DNA para agências, guias e experiências turísticas venderem roteiros, reservas e pacotes digitais.",
    icon: "map-marker-path",
    primaryColor: "#2dd4bf",
    secondaryColor: "#0f172a",
    image: "placeholder://business-dna/turismo",
    maturity: "validated",
    defaultFeatures: ["Roteiros", "Experiências", "Reservas", "Parceiros", "Checkout"],
    availableModules: ["Guias locais", "Agenda", "Combos", "Avaliações", "Mapa interativo"],
    supportedIntegrations: [...commonIntegrations, "Maps"],
    premiumResources: [...commonPremium, "Marketplace de experiências"],
    averageImplementationTime: "8 a 16 dias",
    benefits: ["Vende experiências", "Organiza parceiros", "Cria canal direto"],
    useCases: ["Agências", "Guias", "Rotas turísticas"],
    recommendedPlan: "Growth",
    aiPreparationContract: {
      briefingHints: ["destino", "tipo de experiência", "parceiros"],
      requiredInputs: ["roteiros", "preços", "políticas"],
      suggestedOutputs: ["landing turística", "catálogo de experiências", "campanhas"],
    },
  },
];

export const businessDnaCategories = Array.from(new Set(businessDnaCatalog.map((item) => item.category)));
export const businessDnaSegments = Array.from(new Set(businessDnaCatalog.map((item) => item.segment)));

export function findBusinessDnaBySlug(slug: string) {
  return businessDnaCatalog.find((item) => item.slug === slug);
}
